name: Shared Workflows 1

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.VAR_01 }}
        configuration-path: ${{ inputs.config-path }}
    - name: Hello World!
      run: |
        echo "Hello World!"
