name: Shared Workflows 1

on:
  workflow_call:
    inputs:
      message:
        required: false
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Say hello
      run: |
        echo Hello "${{ message }}"!
